version: "3.9"
services:
  db:
    container_name: unit-postgres
    image: postgres:13-alpine
    ports:
      - 8050:5432
    environment:
      POSTGRES_DB: unit
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password

  redis:
    container_name: unit-redis
    image: redis:6-alpine
    ports:
      - 6395:6379
