/* This file was generated by baeta. Do not edit it directly. */

/* eslint-disable */
/* prettier-ignore */

import "./authentication/authentication.query";

import "./baeta-directives/directives.baeta";

import "./client/client.mutation";

import "./client/client.query";

import "./client/client.subscription";

import "./log/log.mutation";

import "./log/log.query";

import "./log/log.subscription";

import "./message/message.mutation";

import "./message/message.query";

import "./message/message.subscription";

import "./scalars/scalars.resolver";

import "./baeta-directives/directives.baeta";

import {getAuthenticationModule} from "./authentication/typedef";

import {getBaetaDirectivesModule} from "./baeta-directives/typedef";

import {getClientModule} from "./client/typedef";

import {getLogModule} from "./log/typedef";

import {getMessageModule} from "./message/typedef";

import {getScalarsModule} from "./scalars/typedef";

export const modules = [getAuthenticationModule(), getBaetaDirectivesModule(), getClientModule(), getLogModule(), getMessageModule(), getScalarsModule()];
