/* This file was generated by baeta. Do not edit it directly. */

/* eslint-disable */
/* prettier-ignore */

import { getBaetaDirectivesModule } from "./typedef";
import "./directives.baeta.ts";

export const baetaDirectivesModule = getBaetaDirectivesModule();
